config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('ducks/', include('ducks.urls')),
    path('forum/', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.DisplayThreadsView.as_view(), name='list'),
    path('create/', views.CreateThreadView.as_view(), name='create'),
    path('<int:pk>/', views.ThreadDetailsView.as_view(), name='details'),
    path('add-comment/<int:pk>/', views.AddCommentView.as_view(), name='add-comment'),
    path('delete-thread/<int:pk>/', views.DeleteThreadView.as_view(), name='delete-thread'),
    path('delete-comment/<int:pk>/', views.DeleteCommentView.as_view(), name='delete-comment'),
    path('like-comment/<int:thr_pk>/<int:com_pk>/', views.LikeCommentView.as_view(), name='like-comment'),
    path('like-thread/<int:pk>/', views.LikeThreadView.as_view(), name='like-thread'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

home/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.views import View

from forum.models import Thread


class HomeView(View):

    def get(self, request):
        threads = Thread.objects.all().order_by('-likes')

        paginator = Paginator(threads, 20)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'home/home.html', {'page_obj': page_obj})

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    {{ block.super }}
    <div class="row">
        <h2 class="border-bottom border-top border-black p-2">Most popular threads</h2>
    </div>
    <br>
    {% for thread in page_obj %}
        <div class="card align-content-lg-start bg-burlywood m-2">
            <h5 class="card-header">{{ thread.subject }}</h5>
            <div class="card-body">
                <h5 class="card-title">Created by: {{ thread.creator.username }}</h5>
                <p class="card-text">Created at: {{ thread.date_at }}</p>
                <a href="{% url 'forum:details' pk=thread.id %}" class="btn btn-brown">See thread</a>
            </div>
        </div>
    {% empty %}
        <h4>No threads</h4>
    {% endfor %}
    <br>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item bg-burlywood">
                    <a class="page-link bg-burlywood text-black" href="?page={{ page_obj.previous_page_number }}">
                        &laquo;
                    </a>
                </li>
                <li class="page-item bg-burlywood">
                    <a class="page-link bg-burlywood text-black" href="?page={{ page_obj.previous_page_number }}">
                        {{ page_obj.previous_page_number }}
                    </a>
                </li>
            {% endif %}
            <li class="page-item bg-burlywood">
                <a class="page-link text-black" href="?page={{ page_obj.number }}">
                    {{ page_obj.number }}
                </a>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item bg-burlywood">
                    <a class="page-link bg-burlywood text-black" href="?page={{ page_obj.next_page_number }}">
                        {{ page_obj.next_page_number }}
                    </a>
                </li>
                <li class="page-item bg-burlywood">
                    <a class="page-link bg-burlywood text-black" href="?page={{ page_obj.next_page_number }}">
                        &raquo;
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}