config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('ducks/', include('ducks.urls')),
    path('forum/', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ducks/urls.py
from django.urls import path

from . import views

app_name = 'ducks'

urlpatterns = [
    path('add/', views.AddDuckView.as_view(), name='add'),
    path('list/', views.ListDucksView.as_view(), name='list'),
    path('<int:pk>/', views.DuckDetailsView.as_view(), name='details'),
    path('edit/<int:pk>/', views.EditDuckView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.DeleteDuckView.as_view(), name='delete'),
    path('rate/<int:pk>/', views.RateDuckView.as_view(), name='rate'),
]

forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.DisplayThreadsView.as_view(), name='list'),
    path('create/', views.CreateThreadView.as_view(), name='create'),
    path('<int:pk>/', views.ThreadDetailsView.as_view(), name='details'),
    path('add-comment/<int:pk>/', views.AddCommentView.as_view(), name='add-comment'),
    path('delete-thread/<int:pk>/', views.DeleteThreadView.as_view(), name='delete-thread'),
    path('delete-comment/<int:pk>/', views.DeleteCommentView.as_view(), name='delete-comment'),
    path('like-comment/<int:thr_pk>/<int:com_pk>/', views.LikeCommentView.as_view(), name='like-comment'),
    path('like-thread/<int:pk>/', views.LikeThreadView.as_view(), name='like-thread'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('add-fav-duck/<int:pk>/', views.AddFavDuck.as_view(), name='add-fav-duck'),
    path('del-fav-duck/<int:pk>/', views.DelFavDeck.as_view(), name='del-fav-duck'),
]

templates/partials/main-buttons.html
<div class="row mt-5 mb-4">
    <div class="col-5 m-4 p-3 border border-black rounded-2">
        <div class="bg-burlywood">
            <div class="card-body">
                <h5 class="card-title">Start a thread</h5>
                <p class="card-text">Start a thread, but remember - it should be connected with ducks.</p>
                <a href="{% url 'forum:create' %}" class="btn btn-brown">Start Thread</a>
            </div>
        </div>
    </div>
    <div class="col-5 m-4 p-3 border border-black rounded-2">
        <div class="bg-burlywood">
            <div class="card-body">
                <h5 class="card-title">Add a duck</h5>
                <p class="card-text">Add duck to the page. Remember to give some info about it.</p>
                <a href="{% url 'ducks:add' %}" class="btn btn-brown">Add Duck</a>
            </div>
        </div>
    </div>
</div>

templates/partials/messages.html
{% if messages %}
    <div class="container mt-3">
        <div class="row">
            <div class="col">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}

templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-burlywood">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}">
            <img src="{% static 'images/duck-logo3.png' %}" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active m-2" aria-current="page" href="{% url 'home:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active m-2" aria-current="page" href="{% url 'ducks:list' %}">All Ducks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active m-2" aria-current="page" href="{% url 'forum:list' %}">All Threads</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active m-2" aria-current="page" href="{% url 'ducks:add' %}">Add Duck</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active m-2" aria-current="page" href="{% url 'forum:create' %}">
                            Start Thread
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active m-2" aria-current="page" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active m-2" aria-current="page" href="{% url 'users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active m-2" aria-current="page" href="{% url 'users:register' %}">
                            Register
                        </a>
                    </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
                <span class="navbar-text m-2">Logged in {{ user.username }}</span>
            {% endif %}
        </div>
    </div>
</nav>