config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('ducks/', include('ducks.urls')),
    path('forum/', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.DisplayThreadsView.as_view(), name='list'),
    path('create/', views.CreateThreadView.as_view(), name='create'),
    path('<int:pk>/', views.ThreadDetailsView.as_view(), name='details'),
    path('add-comment/<int:pk>/', views.AddCommentView.as_view(), name='add-comment'),
    path('delete-thread/<int:pk>/', views.DeleteThreadView.as_view(), name='delete-thread'),
    path('delete-comment/<int:pk>/', views.DeleteCommentView.as_view(), name='delete-comment'),
    path('like-comment/<int:thr_pk>/<int:com_pk>/', views.LikeCommentView.as_view(), name='like-comment'),
    path('like-thread/<int:pk>/', views.LikeThreadView.as_view(), name='like-thread'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

forum/models.py
from django.core.validators import MinValueValidator
from django.db import models

from config.settings import AUTH_USER_MODEL


class Thread(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    creator = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    likes = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    date_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ('-date_at',)


class Comment(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    thread = models.ForeignKey('Thread', on_delete=models.CASCADE)
    content = models.TextField()
    likes = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    date_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content[:10]


class LikeComment(models.Model):
    comment = models.ForeignKey('Comment', on_delete=models.CASCADE)
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)


class LikeThread(models.Model):
    thread = models.ForeignKey('Thread', on_delete=models.CASCADE)
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)

forum/forms.py
from django import forms

from forum import models


class AddCommentForm(forms.ModelForm):
    content = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={
            'width': 300,
            'height': 50,
            'placeholder': 'Write a comment',
        })
    )

    class Meta:
        model = models.Comment
        fields = ('content',)

forum/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, ListView, DeleteView, DetailView

from forum.models import Thread, Comment, LikeComment, LikeThread
from forum.forms import AddCommentForm
from forum.permissions import ThreadCreatorRequiredMixin, CommentCreatorRequiredMixin


class DisplayThreadsView(ListView):
    model = Thread
    template_name = 'forum/list-threads.html'
    context_object_name = 'threads'
    paginate_by = 20


class CreateThreadView(LoginRequiredMixin, CreateView):
    model = Thread
    fields = ('subject', 'content')
    template_name = 'forum/create-thread.html'
    success_url = reverse_lazy('forum:list')
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.instance.creator = self.request.user
        self.request.user.score = F('score') + 5
        self.request.user.save()
        return super().form_valid(form)


class ThreadDetailsView(DetailView):
    """View for thread details, comments"""

    model = Thread
    template_name = 'forum/thread-details.html'
    context_object_name = 'thread'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['comments'] = Comment.objects.filter(thread_id=kwargs.get('object').pk)
        context['form'] = AddCommentForm
        return context


class AddCommentView(LoginRequiredMixin, CreateView):
    """View for adding comment to thread"""

    form_class = AddCommentForm
    template_name = 'forum/thread-details.html'
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        self.request.user.score = F('score') + 2
        self.request.user.save()
        form.instance.user = self.request.user
        form.instance.thread = Thread.objects.get(pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['thread'] = Thread.objects.get(pk=self.kwargs.get('pk'))
        context['comments'] = Comment.objects.filter(thread_id=kwargs.get('pk'))
        return context

    def get_success_url(self):
        return reverse('forum:details', kwargs={'pk': self.kwargs.get('pk')})

    def get_login_url(self):
        messages.add_message(
            self.request,
            messages.WARNING,
            f'Login in order to add comment'
        )
        return reverse('users:login')


class DeleteThreadView(LoginRequiredMixin, ThreadCreatorRequiredMixin, DeleteView):
    model = Thread
    template_name = 'forum/delete-thread.html'
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy('forum:list')
    context_object_name = 'thread'


class DeleteCommentView(LoginRequiredMixin, CommentCreatorRequiredMixin, DeleteView):
    model = Comment
    template_name = 'forum/delete-comment.html'
    login_url = reverse_lazy('users:login')
    context_object_name = 'comment'

    def get_success_url(self):
        comment_id = self.kwargs.get('pk')
        comment = Comment.objects.get(pk=comment_id)
        pk = comment.thread.id
        return reverse('forum:details', kwargs={'pk': pk})


class LikeCommentView(LoginRequiredMixin, View):
    """View checks if comment is already liked and increments number of likes"""
    login_url = reverse_lazy('users:login')

    def get(self, request, thr_pk, com_pk):
        try:
            comment = Comment.objects.get(pk=com_pk)
        except Comment.DoesNotExist:
            messages.add_message(
                request,
                messages.WARNING,
                f'Comment does not exist'
            )

            if Thread.objects.filter(pk=thr_pk).exists():
                return redirect(reverse('forum:details', kwargs={'pk': thr_pk}))

            return redirect(reverse('forum:list'))

        if not LikeComment.objects.filter(user=request.user, comment=comment).exists():
            LikeComment.objects.create(user=request.user, comment=comment)
            comment.likes = F('likes') + 1
            comment.user.score = F('score') + 1
            comment.user.save()
            comment.save()

        if Thread.objects.filter(pk=thr_pk).exists():
            return redirect(reverse('forum:details', kwargs={'pk': thr_pk}))

        return redirect(reverse('forum:list'))

    def get_login_url(self):
        messages.add_message(
            self.request,
            messages.WARNING,
            f'Login in order to like comment'
        )
        return super().get_login_url()


class LikeThreadView(LoginRequiredMixin, View):
    """View checks if thread is already liked and increments number of likes"""
    login_url = reverse_lazy('users:login')

    def get(self, request, pk):
        try:
            thread = Thread.objects.get(pk=pk)
        except Thread.DoesNotExist:
            messages.add_message(
                request,
                messages.WARNING,
                f'Thread does not exist'
            )

            return redirect(reverse('forum:list'))

        if not LikeThread.objects.filter(user=request.user, thread=thread).exists():
            LikeThread.objects.create(user=request.user, thread=thread)
            thread.likes = F('likes') + 1
            thread.creator.score = F('score') + 1
            thread.creator.save()
            thread.save()

        return redirect(reverse('forum:details', kwargs={'pk': pk}))

    def get_login_url(self):
        messages.add_message(
            self.request,
            messages.WARNING,
            f'Login in order to like thread'
        )
        return super().get_login_url()

forum/templates/forum/create-thread.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}
    Create Thread
{% endblock %}

{% block content %}
    <div class="row">
        <h2 class="border-bottom border-top border-black p-2">Start Thread</h2>
    </div>
    <div class="lm m-3">
        <form action="" method="post" class="m-3">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-brown" type="submit">Start Thread</button>
        </form>
    </div>
{% endblock %}

forum/templates/forum/delete-comment.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}
    Delete Comment
{% endblock %}

{% block content %}
    <div class="text-center p-3 border border-black rounded-2">
        <div class="card-body bg-burlywood">
            <h5 class="card-title">Are you sure?</h5>
            <p class="card-text">This comment will be deleted, you cannot reverse this action.</p>
            <form action="" method="post">
                {% csrf_token %}
                <a href="{% url 'forum:details' pk=comment.thread.id %}" class="btn me-4 btn-brown">Cancel</a>
                <button type="submit" class="btn ms-4 btn-danger">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

forum/templates/forum/delete-thread.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}
    Delete Thread
{% endblock %}

{% block content %}
    <div class="text-center p-3 border border-black rounded-2">
        <div class="card-body bg-burlywood">
            <h5 class="card-title">Are you sure?</h5>
            <p class="card-text">This thread will be deleted, you cannot reverse this action.</p>
            <form action="" method="post">
                {% csrf_token %}
                <a href="{% url 'forum:details' pk=thread.id %}" class="btn me-4 btn-brown">Cancel</a>
                <button type="submit" class="btn ms-4 btn-danger">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

forum/templates/forum/list-threads.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}
    Threads
{% endblock %}

{% block content %}
    {{ block.super }}
    <div class="row">
        <h2 class="border-bottom border-top border-black p-2">All Threads</h2>
    </div>
    {% for thread in threads %}
        <div class="card align-content-lg-start bg-burlywood m-2">
            <h5 class="card-header">{{ thread.subject }}</h5>
            <div class="card-body">
                <h5 class="card-title">Created by: {{ thread.creator.username }}</h5>
                <p class="card-text">Created at: {{ thread.date_at }}</p>
                <a href="{% url 'forum:details' pk=thread.id %}" class="btn btn-brown">See thread</a>
            </div>
        </div>
    {% empty %}
        <h4>No threads</h4>
    {% endfor %}
    <br>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item bg-burlywood">
                    <a class="page-link bg-burlywood text-black" href="?page={{ page_obj.previous_page_number }}">
                        &laquo;
                    </a>
                </li>
                <li class="page-item bg-burlywood">
                    <a class="page-link bg-burlywood text-black" href="?page={{ page_obj.previous_page_number }}">
                        {{ page_obj.previous_page_number }}
                    </a>
                </li>
            {% endif %}
            <li class="page-item bg-burlywood">
                <a class="page-link text-black" href="?page={{ page_obj.number }}">
                    {{ page_obj.number }}
                </a>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item bg-burlywood">
                    <a class="page-link bg-burlywood text-black" href="?page={{ page_obj.next_page_number }}">
                        {{ page_obj.next_page_number }}
                    </a>
                </li>
                <li class="page-item bg-burlywood">
                    <a class="page-link bg-burlywood text-black" href="?page={{ page_obj.next_page_number }}">
                        &raquo;
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

forum/templates/forum/thread-details.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}
    {{ thread.subject }}
{% endblock %}

{% block content %}
    {{ block.super }}
    <div class="border border-black rounded-2">
        <div class="p-2 d-flex justify-content-sm-start" role="group" aria-label="Basic example">
            <p class="d-inline me-5">Thread started by: <b>{{ thread.creator }}</b></p>
            {% if user.pk == thread.creator.pk or user.is_superuser %}
                <a href="{% url 'forum:delete-thread' pk=thread.pk %}" class="btn btn-brown me-5">Delete</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a href="{% url 'forum:like-thread' pk=thread.pk %}" class="btn btn-brown">Like Thread</a>
            {% endif %}
        </div>
        <h3 class="p-2 border-top border-bottom border-black">{{ thread.subject.title }}</h3>
        <div class="container mb-2 text-lg-start">
            <p>{{ thread.content }}</p>
        </div>
        <div class="container p-1 pt-5 d-flex justify-content-between">
            <p class="ms-2">Thread started at: {{ thread.date_at }}</p>
            <p class="me-5">Likes: {{ thread.likes }}</p>
        </div>
    </div>
    <br>
    {% if user.is_authenticated %}
        <form action="{% url 'forum:add-comment' pk=thread.pk %}" method="post" class="d-inline">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-brown" type="submit">Add Comment</button>
        </form>
    {% endif %}
    <br>
    <h4 class="m-3 p-2 border-top border-bottom border-black">Answers</h4>
    {% for comment in comments %}
        <div class="p-2 border border-black rounded-2 mb-2 mt-2">
            <div class="p-1 d-flex justify-content-sm-start border-bottom border-black">
                <h6 class="card-header ">{{ comment.user }} ({{ comment.date_at }})</h6>
            </div>
            <div class="p-1 d-flex justify-content-sm-start">
                <p class="d-inline me-2">{{ comment.content }}</p>
            </div>
            <div class="d-flex justify-content-between">
                {% if user.is_authenticated %}
                    <a href="{% url 'forum:like-comment' thr_pk=thread.pk com_pk=comment.pk %}" class="btn btn-brown">
                        Like Comment
                    </a>
                {% endif %}
                {% if user.pk == comment.user.pk or user.is_superuser %}
                    <a href="{% url 'forum:delete-comment' pk=comment.pk %}" class="btn btn-brown me-5">Delete</a>
                {% endif %}
                <p class="d-inline me-5">Likes: {{ comment.likes }}</p>
            </div>
        </div>
    {% empty %}
        <p>No comments</p>
    {% endfor %}
{% endblock %}