config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('ducks/', include('ducks.urls')),
    path('forum/', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ducks/urls.py
from django.urls import path

from . import views

app_name = 'ducks'

urlpatterns = [
    path('add/', views.AddDuckView.as_view(), name='add'),
    path('list/', views.ListDucksView.as_view(), name='list'),
    path('<int:pk>/', views.DuckDetailsView.as_view(), name='details'),
    path('edit/<int:pk>/', views.EditDuckView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.DeleteDuckView.as_view(), name='delete'),
    path('rate/<int:pk>/', views.RateDuckView.as_view(), name='rate'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('add-fav-duck/<int:pk>/', views.AddFavDuck.as_view(), name='add-fav-duck'),
    path('del-fav-duck/<int:pk>/', views.DelFavDeck.as_view(), name='del-fav-duck'),
]

ducks/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from config.settings import AUTH_USER_MODEL


class Duck(models.Model):
    """model representing duck"""

    name = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='ducks')
    origin_country = models.CharField(max_length=200, blank=True)
    avg_weight = models.DecimalField(validators=[MinValueValidator(0)], max_digits=3, decimal_places=1)
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    strength = models.DecimalField(
        validators=[MinValueValidator(0), MaxValueValidator(10.0)],
        max_digits=3,
        decimal_places=1
    )
    agility = models.DecimalField(
        validators=[MinValueValidator(0), MaxValueValidator(10.0)],
        max_digits=3,
        decimal_places=1
    )
    intelligence = models.DecimalField(
        validators=[MinValueValidator(0), MaxValueValidator(10.0)],
        max_digits=3,
        decimal_places=1
    )
    charisma = models.DecimalField(
        validators=[MinValueValidator(0), MaxValueValidator(10.0)],
        max_digits=3,
        decimal_places=1
    )
    date_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-date_at',)
        

class DuckRate(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    duck = models.ForeignKey('Duck', on_delete=models.CASCADE)
    rate = models.DecimalField(
        validators=[MinValueValidator(0), MaxValueValidator(10.0)],
        max_digits=3,
        decimal_places=1
    )

    def __str__(self):
        return f'{self.duck.name} - {str(self.rate)}'

ducks/forms.py
from django import forms
from django.core.exceptions import ValidationError

from ducks import models


class AddDuckForm(forms.ModelForm):
    """Add Duck Form"""

    origin_country = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'placeholder': 'If unknown, leave blank'
        })
    )

    class Meta:
        model = models.Duck
        fields = (
            'name',
            'description',
            'origin_country',
            'image',
            'avg_weight',
            'strength',
            'agility',
            'intelligence',
            'charisma'
        )

    def clean_name(self):
        name = self.cleaned_data.get('name')

        if name and models.Duck.objects.filter(name=name.lower()).exists():
            raise ValidationError(f'This duck already in database')

        return name.lower()

    def clean_origin_country(self):
        origin_country = self.cleaned_data.get('origin_country')

        if not origin_country:
            return 'Unknown'

        return origin_country

    def save(self, commit=True):
        duck = super().save(commit=False)
        duck.origin_country = self.clean_origin_country()
        duck.name = self.cleaned_data.get('name').lower()

        if commit:
            super().save()

        return duck


class EditDuckForm(AddDuckForm):
    """class for editing duck"""

    class Meta(AddDuckForm.Meta):
        fields = (
            'name',
            'description',
            'origin_country',
            'avg_weight',
            'strength',
            'agility',
            'intelligence',
            'charisma'
        )


class RateDuckForm(forms.ModelForm):
    choices = []
    for i in range(1, 11):
        choices.append((i, '\N{white medium star}' * i))

    rate = forms.ChoiceField(
        label='Rate Duck',
        choices=choices
    )

    class Meta:
        model = models.DuckRate
        fields = ('rate',)

ducks/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F, Sum
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView

from ducks.forms import AddDuckForm, RateDuckForm, EditDuckForm
from ducks.models import Duck, DuckRate
from ducks.permissions import DuckCreatorRequiredMixin


class AddDuckView(LoginRequiredMixin, CreateView):
    """View for adding duck to database"""

    form_class = AddDuckForm
    template_name = 'ducks/add-duck.html'
    context_object_name = 'form'
    success_url = reverse_lazy('ducks:list')
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        self.request.user.score = F('score') + 2
        self.request.user.save()
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            f'Successfully added duck')
        return super().get_success_url()

    def handle_no_permission(self):
        messages.add_message(
            self.request,
            messages.WARNING,
            f'Login in order to add duck'
        )
        return super().handle_no_permission()


class ListDucksView(ListView):
    """lists all ducks with their photos and link to duck-details page"""

    model = Duck
    template_name = 'ducks/list-ducks.html'
    context_object_name = 'ducks'
    paginate_by = 12


class DuckDetailsView(DetailView):
    """displays details about a duck"""

    model = Duck
    template_name = 'ducks/duck-details.html'
    context_object_name = 'duck'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        duck = context.get('duck')

        owner = False
        favorite = False
        if self.request.user.is_authenticated:
            if self.request.user.pk == duck.user.pk or self.request.user.is_superuser:
                owner = True
            if duck in self.request.user.fav_ducks.all():
                favorite = True
        context['owner'] = owner
        context['favorite'] = favorite

        rates = DuckRate.objects.filter(duck=duck)
        if rates:
            rates_sum = rates.aggregate(Sum('rate'))
            duck_rate = float(rates_sum['rate__sum']) / rates.count()
            duck_rate = round(duck_rate, 1)
        else:
            duck_rate = 0
        context['rate'] = duck_rate

        overall_stats = (duck.strength + duck.agility + duck.intelligence + duck.charisma) / 4
        overall_stats = round(overall_stats, 1)
        context['overall'] = overall_stats

        rate_form = RateDuckForm()
        context['form'] = rate_form

        return context


class EditDuckView(LoginRequiredMixin, DuckCreatorRequiredMixin, UpdateView):
    """View for editing duck"""

    model = Duck
    form_class = EditDuckForm
    template_name = 'ducks/edit-duck.html'
    context_object_name = 'form'
    login_url = reverse_lazy('users:login')

    def get_success_url(self):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            f'Successfully edited duck'
        )
        return reverse('ducks:details', kwargs={'pk': self.kwargs.get('pk')})

    def get_login_url(self):
        messages.add_message(
            self.request,
            messages.WARNING,
            f'You must login in order to edit this duck'
        )
        return super().get_login_url()


class DeleteDuckView(LoginRequiredMixin, DuckCreatorRequiredMixin, DeleteView):
    """View for deleting duck"""

    model = Duck
    template_name = 'ducks/delete-duck.html'
    context_object_name = 'duck'
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy('ducks:list')

    def get_login_url(self):
        messages.add_message(
            self.request,
            messages.WARNING,
            f'If you want to delete this duck, you must login'
        )
        return super().get_login_url()

    def get_success_url(self):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            f'Successfully deleted duck'
        )
        return super().get_success_url()


class RateDuckView(LoginRequiredMixin, View):
    """View rates duck in scale 1-10"""
    login_url = reverse_lazy('users:login')

    def post(self, request, pk):
        try:
            duck = Duck.objects.get(pk=pk)
        except Duck.DoesNotExist:
            messages.add_message(request,
                                 messages.WARNING,
                                 f'Sorry, we lost this duck')

            return redirect(reverse('home:home'))

        form = RateDuckForm(request.POST)

        if form.is_valid():
            if DuckRate.objects.filter(user=request.user, duck=duck).exists():
                messages.add_message(request,
                                     messages.WARNING,
                                     f'You have already rated {duck.name.title()}')

                return redirect(reverse('ducks:details', kwargs={'pk': pk}))

            rate = form.save(commit=False)

            rate.user = request.user
            rate.duck = duck

            form.save()

            return redirect(reverse('ducks:details', kwargs={'pk': pk}))

    def get_login_url(self):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            f'Login in order to rate this duck'
        )
        return super().get_login_url()

ducks/templates/ducks/add-duck.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}
    Add Duck
{% endblock %}

{% block content %}
    <div class="row">
        <h2 class="border-bottom border-top border-black p-2">Add Duck</h2>
    </div>
    <div class="lm m-3">
        <form action="" method="post" class="m-3" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-brown" type="submit">Add Duck</button>
        </form>
    </div>
{% endblock %}

ducks/templates/ducks/delete-duck.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}
    Delete Duck
{% endblock %}

{% block content %}
    <div class="text-center p-3 border border-black rounded-2">
        <div class="card-body bg-burlywood">
            <h5 class="card-title">Are you sure?</h5>
            <p class="card-text">Duck {{ duck.name.title }} will be deleted, you cannot reverse this action.</p>
            <form action="" method="post">
                {% csrf_token %}
                <a href="{% url 'ducks:details' pk=duck.id %}" class="btn me-4 btn-brown">Cancel</a>
                <button type="submit" class="btn ms-4 btn-danger">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

ducks/templates/ducks/duck-details.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}
    {{ duck.name.title }}
{% endblock %}

{% block content %}
    {{ block.super }}
    <div class="mt-5 mb-3 container text-lg-start" role="group" aria-label="Basic example">
        {% if owner %}
            <a href="{% url 'ducks:delete' pk=duck.id %}" class="btn btn-brown">Delete</a>
            <a href="{% url 'ducks:edit' pk=duck.id %}" class="btn btn-brown">Edit</a>
        {% endif %}
        {% if user.is_authenticated %}
            {% if not favorite %}
                <a href="{% url 'users:add-fav-duck' pk=duck.id %}" class="btn btn-brown">Add to Favorites</a>
            {% else %}
                <a href="{% url 'users:del-fav-duck' pk=duck.id %}" class="btn btn-brown">Delete from Favorites</a>
            {% endif %}
        {% endif %}
    </div>
    <h3 class="p-2 border-bottom border-black">{{ duck.name.title }}</h3>
    <div class="container mb-5 text-lg-start">
        <p>{{ duck.description }}</p>
    </div>
    <div class="container pt-5 text-lg-start">
        <p>Duck added at: {{ duck.date_at }}</p>
    </div>
    <br>
    <div class="row">
        <div class="col-2 text-lg-start">
            <form action="/ducks/rate/{{ duck.id }}/" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-brown">Rate</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block right-side %}
    {{ block.super }}
    <div class="border border-black">
        <div class="m-3">
            <img src="{{ duck.image.url }}" class="img-duck-details" alt="{{ duck.name }}">
        </div>
        <div class="container text-lg-start">
            <h5 class="mt-3 p-2 text-center border-top border-bottom border-black">INFO</h5>
            <ul style="list-style-type: none">
                <li><b>Name:</b> {{ duck.name.title }}</li>
                <li><b>Origin country:</b> {{ duck.origin_country }}</li>
                <li><b>Average weight:</b> {{ duck.avg_weight }}</li>
            </ul>
            <h5 class="mt-3 p-2 text-center border-top border-bottom border-black">STATS</h5>
            <ul style="list-style-type: none">
                <li><b>Strength:</b> {{ duck.strength }}/10</li>
                <li><b>Agility:</b> {{ duck.agility }}/10</li>
                <li><b>Intelligence:</b> {{ duck.intelligence }}/10</li>
                <li><b>Charisma:</b> {{ duck.charisma }}/10</li>
                <li><b>Overall:</b> {{ overall }}/10</li>
            </ul>
            <h5 class="mt-3 p-2 text-center border-top border-bottom border-black">RATE</h5>
            <ul style="list-style-type: none">
                <li><b>Rate:</b> {{ rate }}/10</li>
            </ul>
        </div>
    </div>
{% endblock %}

ducks/templates/ducks/edit-duck.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}
    Edit Duck
{% endblock %}

{% block content %}
    <div class="row">
        <h2 class="border-bottom border-top border-black p-2">Edit Duck</h2>
    </div>
    <div class="lm m-3">
        <form action="" method="post" class="m-3" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-brown" type="submit">Edit Duck</button>
        </form>
    </div>
{% endblock %}

ducks/templates/ducks/list-ducks.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}
    Ducks
{% endblock %}

{% block content %}
    {{ block.super }}
    <div class="row">
        <h2 class="border-bottom border-top border-black p-2">All Ducks</h2>
    </div>
    <div class="row justify-content-evenly mt-5 mb-5">
        {% for duck in ducks %}
            <div class="justify-content-center mt-4" style="width: 18rem;">
                <img src="{{ duck.image.url }}" class="img-duck-list" alt="{{ duck.name }}">
                <div class="card-body mt-2">
                    <a href="{% url 'ducks:details' pk=duck.id %}" class="btn btn-brown">{{ duck.name.title }}</a>
                </div>
            </div>
        {% empty %}
            <h4>No Ducks</h4>
        {% endfor %}
    </div>
    <br>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item bg-burlywood">
                    <a class="page-link bg-burlywood text-black" href="?page={{ page_obj.previous_page_number }}">
                        &laquo;
                    </a>
                </li>
                <li class="page-item bg-burlywood">
                    <a class="page-link bg-burlywood text-black" href="?page={{ page_obj.previous_page_number }}">
                        {{ page_obj.previous_page_number }}
                    </a>
                </li>
            {% endif %}
            <li class="page-item bg-burlywood">
                <a class="page-link text-black" href="?page={{ page_obj.number }}">
                    {{ page_obj.number }}
                </a>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item bg-burlywood">
                    <a class="page-link bg-burlywood text-black" href="?page={{ page_obj.next_page_number }}">
                        {{ page_obj.next_page_number }}
                    </a>
                </li>
                <li class="page-item bg-burlywood">
                    <a class="page-link bg-burlywood text-black" href="?page={{ page_obj.next_page_number }}">
                        &raquo;
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}